version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
      build:
        context: .
        dockerfile: docker/Dockerfile.backend
      restart: always
      container_name: backend-service
      ports:
      - 8080:8080
      environment: 
        - DATABASE_URL="postgresql://neondb_owner:npg_htmOvXAqG04a@ep-calm-union-a5688dly-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
        - WEBHOOK_BASE_URL="https://localhost:8080"
        - S3_ACCESS_KEY="AKIA47CRY7P5OVCBWYRH"
        - S3_SECRET_KEY="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"
        - ENDPOINT="https://image-gen-files.s3.us-east-1.amazonaws.com"
        - BUCKET_NAME="image-gen-files"
        - REGION="us-east-1"
        - FAL_KEY = "4d4bb721-e7eb-4dbf-8072-ec813a9cb714:c893dda05ded8f3862bac8125355c2e8"
        - CLERK_PUBLISHABLE_KEY="pk_test_bG9naWNhbC1icmVhbS03Ny5jbGVyay5hY2NvdW50cy5kZXYk"
        - CLERK_SECRET_KEY="sk_test_BYbbTJ9oK79aDyXkKAcQSAIaIV5sIJhR20Qi9RaVzI"
        - CLERK_JWT_PUBLIC_KEY="pk_test_bG9naWNhbC1icmVhbS03Ny5jbGVyay5hY2NvdW50cy5kZXYk"